problems = {
    "Set Matrix Zeros": "https://leetcode.com/problems/set-matrix-zeroes/",
    "Pascal's Triangle": "https://leetcode.com/problems/pascals-triangle/",
    "Next Permutation": "https://leetcode.com/problems/next-permutation/",
    "Kadane's Algorithm": "https://leetcode.com/problems/maximum-subarray/",
    "Sort an array of 0's, 1's and 2's": "https://leetcode.com/problems/sort-colors/",
    "Stock Buy and Sell": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    "Rotate Matrix": "https://leetcode.com/problems/rotate-image/",
    "Merge Overlapping Subintervals": "https://leetcode.com/problems/merge-intervals/",
    "Merge two sorted arrays without extra space": "https://leetcode.com/problems/merge-sorted-array/",
    "Find the duplicate in an array of N+1 integers": "https://leetcode.com/problems/find-the-duplicate-number/",
    "Search in a 2 D matrix": "https://leetcode.com/problems/search-a-2d-matrix/",
    "Pow(x, n)": "https://leetcode.com/problems/powx-n/",
    "Majority Element (>n/2 times)": "https://leetcode.com/problems/majority-element/",
    "Majority Element (n/3 times)": "https://leetcode.com/problems/majority-element-ii/",
    "Grid Unique Paths": "https://leetcode.com/problems/unique-paths/",
    "Reverse Pairs (Leetcode)": "https://leetcode.com/problems/reverse-pairs/",
    "2Sum Problem": "https://leetcode.com/problems/two-sum/",
    "4-Sum Problem": "https://leetcode.com/problems/4sum/",
    "Longest Consecutive Sequence": "https://leetcode.com/problems/longest-consecutive-sequence/",
    "Longest Substring without repeat": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "Reverse a LinkedList": "https://leetcode.com/problems/reverse-linked-list/",
    "Find the middle of LinkedList": "https://leetcode.com/problems/middle-of-the-linked-list/",
    "Merge two sorted Linked List (use method used in mergeSort)": "https://leetcode.com/problems/merge-two-sorted-lists/",
    "Remove N-th node from back of LinkedList": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "Add two numbers as LinkedList": "https://leetcode.com/problems/add-two-numbers/",
    "Delete a given Node when a node is given.(0(1) solution)": "https://leetcode.com/problems/delete-node-in-a-linked-list/",
    "Find intersection point of Y LinkedList": "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    "Detect a cycle in Linked List": "https://leetcode.com/problems/linked-list-cycle/",
    "Reverse a LinkedList in groups of size k.": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    "Check if a LinkedList is palindrome or not.": "https://leetcode.com/problems/palindrome-linked-list/",
    "Find the starting point of the Loop of LinkedList": "https://leetcode.com/problems/linked-list-cycle-ii/",
    "Rotate a LinkedList": "https://leetcode.com/problems/rotate-list/description/",
    "Clone a Linked List with random and next pointer": "https://leetcode.com/problems/copy-list-with-random-pointer/",
    "3 sum": "https://leetcode.com/problems/3sum/",
    "Trapping Rainwater": "https://leetcode.com/problems/trapping-rain-water/",
    "Remove Duplicate from Sorted array": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    "Max consecutive ones": "https://leetcode.com/problems/max-consecutive-ones/",
    "Assign Cookies": "https://leetcode.com/problems/assign-cookies/",
    "Subset-II": "https://leetcode.com/problems/subsets-ii/",
    "Combination sum-1": "https://leetcode.com/problems/combination-sum/",
    "Combination sum-2": "https://leetcode.com/problems/combination-sum-ii/",
    "Palindrome Partitioning": "https://leetcode.com/problems/palindrome-partitioning/",
    "K-th permutation Sequence": "https://leetcode.com/problems/permutation-sequence/",
    "Print all permutations of a string/array": "https://leetcode.com/problems/permutations/",
    "N queens Problem": "https://leetcode.com/problems/n-queens/",
    "Sudoko Solver": "https://leetcode.com/problems/sudoku-solver/",
    "Find the element that appears once in a sorted array, and the rest element appears twice (Binary search)": "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    "Search element in a sorted and rotated array/ find pivot where it is rotated": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "Median of 2 sorted arrays": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    "Kth Largest Element": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    "Find Median from Data Stream": "https://leetcode.com/problems/find-median-from-data-stream/",
    "K most frequent elements": "https://leetcode.com/problems/top-k-frequent-elements/",
    "Implement Stack using Queue (using single queue)": "https://leetcode.com/problems/implement-stack-using-queues/",
    "Implement Queue using Stack (0(1) amortized method)": "https://leetcode.com/problems/implement-queue-using-stacks/",
    "Check for balanced parentheses": "https://leetcode.com/problems/valid-parentheses/",
    "Next Greater Element": "https://leetcode.com/problems/next-greater-element-i/",
    "LRU cache (IMPORTANT)": "https://leetcode.com/problems/lru-cache/",
    "LFU cache": "https://leetcode.com/problems/lfu-cache/",
    "Largest rectangle in a histogram": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    "Sliding Window maximum": "https://leetcode.com/problems/sliding-window-maximum/",
    "Implement Min Stack": "https://leetcode.com/problems/min-stack/",
    "Rotten Orange (Using BFS)": "https://leetcode.com/problems/rotting-oranges/",
    "Stock span problem": "https://leetcode.com/problems/online-stock-span/",
    "The Celebrity Problem": "https://leetcode.com/accounts/login/?next=/problems/find-the-celebrity/",
    "Reverse Words in a String": "https://leetcode.com/problems/reverse-words-in-a-string/",
    "Longest Palindrome in a string": "https://leetcode.com/problems/longest-palindromic-substring/",
    "Roman Number to Integer and vice versa": "https://leetcode.com/problems/roman-to-integer/",
    "Implement ATOI/STRSTR": "https://leetcode.com/problems/string-to-integer-atoi/",
    "Longest Common Prefix": "https://leetcode.com/problems/longest-common-prefix/",
    "Rabin Karp": "https://leetcode.com/problems/repeated-string-match/discuss/416144/Rabin-Karp-algorithm-C%2B%2B-implementation",
    "Z-Function": "https://leetcode.com/problems/implement-strstr/",
    "KMP algo / LPS(pi) array": "https://leetcode.com/problems/implement-strstr/",
    "Check for Anagrams": "https://leetcode.com/problems/valid-anagram/",
    "Count and say": "https://leetcode.com/problems/count-and-say/",
    "Compare version numbers": "https://leetcode.com/problems/compare-version-numbers/",
    "Inorder Traversal": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    "Preorder Traversal": "https://leetcode.com/problems/binary-tree-preorder-traversal/",
    "Postorder Traversal": "https://leetcode.com/problems/binary-tree-postorder-traversal/",
    "Morris Inorder Traversal": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    "Vertical order traversal": "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
    "Max width of a Binary Tree": "https://leetcode.com/problems/maximum-width-of-binary-tree/",
    "Level order Traversal / Level order traversal in spiral form": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "Height of a Binary Tree": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    "Diameter of Binary Tree": "https://leetcode.com/problems/diameter-of-binary-tree/",
    "Check if the Binary tree is height-balanced or not": "https://leetcode.com/problems/balanced-binary-tree/",
    "LCA in Binary Tree": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    "Check if two trees are identical or not": "https://leetcode.com/problems/same-tree/",
    "Zig Zag Traversal of Binary Tree": "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    "Boundary Traversal of Binary Tree": "https://leetcode.com/problems/boundary-of-binary-tree/",
    "Maximum path sum": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "Construct Binary Tree from inorder and preorder": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    "Construct Binary Tree from Inorder and Postorder": "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
    "Symmetric Binary Tree": "https://leetcode.com/problems/symmetric-tree/",
    "Flatten Binary Tree to LinkedList": "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
    "Populate Next Right pointers of Tree": "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
    "Search given Key in BST": "https://leetcode.com/problems/search-in-a-binary-search-tree/",
    "Construct BST from given keys": "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
    "Construct a BST from a preorder traversal": "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/",
    "Check is a BT is BST or not": "https://leetcode.com/problems/validate-binary-search-tree/",
    "Find LCA of two nodes in BST": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    "Find K-th smallest element in BST": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    "Find a pair with a given sum in BST": "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
    "BST iterator": "https://leetcode.com/problems/binary-search-tree-iterator/",
    "Size of the largest BST in a Binary Tree": "https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/",
    "Serialize and deserialize Binary Tree": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "Binary Tree to Double Linked List": "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
    "Find median in a stream of running integers.": "https://leetcode.com/problems/find-median-from-data-stream/",
    "K-th largest element in a stream.": "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    "K-th largest element in an unsorted array.": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    "Flood-fill Algorithm": "https://leetcode.com/problems/flood-fill/",
    "Clone a graph (Not that easy as it looks)": "https://leetcode.com/problems/clone-graph/",
    "Detect A cycle in Undirected Graph using BFS": "https://leetcode.com/problems/course-schedule/",
    "Detect A cycle in Undirected Graph using DFS": "https://leetcode.com/problems/course-schedule/",
    "Detect A cycle in a Directed Graph using DFS": "https://leetcode.com/problems/course-schedule/",
    "Detect A cycle in a Directed Graph using BFS": "https://leetcode.com/problems/course-schedule/",
    "Number of islands(Do in Grid and Graph Both)": "https://leetcode.com/problems/number-of-islands/",
    "Bipartite Check using BFS": "https://leetcode.com/problems/is-graph-bipartite/",
    "Bipartite Check using DFS": "https://leetcode.com/problems/is-graph-bipartite/",
    "Strongly Connected Component(using KosaRajuΓÇÖs algo)": "https://leetcode.com/problems/maximum-number-of-non-overlapping-substrings/discuss/766485/kosaraju-algorithm-on",
    "Max Product Subarray": "https://leetcode.com/problems/maximum-product-subarray/",
    "Longest Increasing Subsequence": "https://leetcode.com/problems/longest-increasing-subsequence/",
    "Longest Common Subsequence": "https://leetcode.com/problems/longest-common-subsequence/",
    "Edit Distance": "https://leetcode.com/problems/edit-distance/",
    "Minimum sum path in the matrix, (count paths and similar type do, also backtrack to find the Minimum path)": "https://leetcode.com/problems/minimum-path-sum/",
    "Coin change": "https://leetcode.com/problems/coin-change/",
    "Subset Sum": "https://leetcode.com/problems/partition-equal-subset-sum/",
    "Rod Cutting": "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
    "Word Break": "https://leetcode.com/problems/word-break/",
}
